version: '3.1'


services:
  webui:
    build: src/WebUi
    ports:
      - "3000:3000"
    networks:
      - app
    environment:
      API_URL: http://api:5000

  solgen-api:
    build: src/Solgen
    ports:
      - "5000:5000"
    networks:
      - app

networks:
  app: