version: '3.1'


services:
  ui:
    build: src/WebUi
    ports:
      - "3000:3000"
    networks:
      - app
    environment:
      API_URL: http://api:5000

  api:
    build: src/Solgen
    ports:
      - "5000:5000"
    networks:
      - app
  database:
    image: postgres
    networks:
      - app
    ports:
      - "5432:5432"

networks:
  app: